#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="jobportal")]
public partial class DataClasses2DataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertTbl_jobseeker(Tbl_jobseeker instance);
  partial void UpdateTbl_jobseeker(Tbl_jobseeker instance);
  partial void DeleteTbl_jobseeker(Tbl_jobseeker instance);
  #endregion
	
	public DataClasses2DataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Tbl_jobseeker> Tbl_jobseekers
	{
		get
		{
			return this.GetTable<Tbl_jobseeker>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertTbl_jobseeker")]
	public int insertTbl_jobseeker(
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email_id", DbType="VarChar(50)")] string email_id, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pwd", DbType="VarChar(20)")] string pwd, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fname", DbType="VarChar(50)")] string fname, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mname", DbType="VarChar(50)")] string mname, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lname", DbType="VarChar(50)")] string lname, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="VarChar(50)")] string gender, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="VarChar(50)")] string address, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Country_id", DbType="VarChar(20)")] string country_id, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="State_id", DbType="VarChar(20)")] string state_id, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="City_id", DbType="VarChar(20)")] string city_id, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contect_no", DbType="VarChar(10)")] string contect_no, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Dob", DbType="VarChar(20)")] string dob, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Blood_group", DbType="VarChar(20)")] string blood_group, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Postal_address", DbType="VarChar(20)")] string postal_address, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Total_expr", DbType="VarChar(20)")] string total_expr, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sque_id", DbType="VarChar(20)")] string sque_id, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ans", DbType="VarChar(20)")] string ans)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email_id, pwd, fname, mname, lname, gender, address, country_id, state_id, city_id, contect_no, dob, blood_group, postal_address, total_expr, sque_id, ans);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertTbl_jobseeker")]
	public int insertTbl_jobseeker1(
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email_id", DbType="VarChar(50)")] string email_id, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pwd", DbType="VarChar(20)")] string pwd, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fname", DbType="VarChar(50)")] string fname, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mname", DbType="VarChar(50)")] string mname, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lname", DbType="VarChar(50)")] string lname, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="VarChar(50)")] string gender, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="VarChar(50)")] string address, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Country_id", DbType="VarChar(20)")] string country_id, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="State_id", DbType="VarChar(20)")] string state_id, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="City_id", DbType="VarChar(20)")] string city_id, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contect_no", DbType="VarChar(10)")] string contect_no, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Dob", DbType="VarChar(20)")] string dob, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Blood_group", DbType="VarChar(20)")] string blood_group, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Postal_address", DbType="VarChar(20)")] string postal_address, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Total_expr", DbType="VarChar(20)")] string total_expr, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sque_id", DbType="VarChar(20)")] string sque_id, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ans", DbType="VarChar(20)")] string ans)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email_id, pwd, fname, mname, lname, gender, address, country_id, state_id, city_id, contect_no, dob, blood_group, postal_address, total_expr, sque_id, ans);
		return ((int)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_jobseeker")]
public partial class Tbl_jobseeker : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Js_id;
	
	private System.Nullable<int> _Email_id;
	
	private string _Pwd;
	
	private string _Fname;
	
	private string _Mname;
	
	private string _Lname;
	
	private string _Gender;
	
	private string _Address;
	
	private System.Nullable<int> _Country_id;
	
	private System.Nullable<int> _State_id;
	
	private System.Nullable<int> _City_id;
	
	private string _Contact_no;
	
	private string _Dob;
	
	private string _Blood_group;
	
	private string _Postal_address;
	
	private string _Total_exper;
	
	private System.Nullable<int> _Sque_id;
	
	private string _Ans;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJs_idChanging(int value);
    partial void OnJs_idChanged();
    partial void OnEmail_idChanging(System.Nullable<int> value);
    partial void OnEmail_idChanged();
    partial void OnPwdChanging(string value);
    partial void OnPwdChanged();
    partial void OnFnameChanging(string value);
    partial void OnFnameChanged();
    partial void OnMnameChanging(string value);
    partial void OnMnameChanged();
    partial void OnLnameChanging(string value);
    partial void OnLnameChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnCountry_idChanging(System.Nullable<int> value);
    partial void OnCountry_idChanged();
    partial void OnState_idChanging(System.Nullable<int> value);
    partial void OnState_idChanged();
    partial void OnCity_idChanging(System.Nullable<int> value);
    partial void OnCity_idChanged();
    partial void OnContact_noChanging(string value);
    partial void OnContact_noChanged();
    partial void OnDobChanging(string value);
    partial void OnDobChanged();
    partial void OnBlood_groupChanging(string value);
    partial void OnBlood_groupChanged();
    partial void OnPostal_addressChanging(string value);
    partial void OnPostal_addressChanged();
    partial void OnTotal_experChanging(string value);
    partial void OnTotal_experChanged();
    partial void OnSque_idChanging(System.Nullable<int> value);
    partial void OnSque_idChanged();
    partial void OnAnsChanging(string value);
    partial void OnAnsChanged();
    #endregion
	
	public Tbl_jobseeker()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Js_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Js_id
	{
		get
		{
			return this._Js_id;
		}
		set
		{
			if ((this._Js_id != value))
			{
				this.OnJs_idChanging(value);
				this.SendPropertyChanging();
				this._Js_id = value;
				this.SendPropertyChanged("Js_id");
				this.OnJs_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email_id", DbType="Int")]
	public System.Nullable<int> Email_id
	{
		get
		{
			return this._Email_id;
		}
		set
		{
			if ((this._Email_id != value))
			{
				this.OnEmail_idChanging(value);
				this.SendPropertyChanging();
				this._Email_id = value;
				this.SendPropertyChanged("Email_id");
				this.OnEmail_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pwd", DbType="NVarChar(50)")]
	public string Pwd
	{
		get
		{
			return this._Pwd;
		}
		set
		{
			if ((this._Pwd != value))
			{
				this.OnPwdChanging(value);
				this.SendPropertyChanging();
				this._Pwd = value;
				this.SendPropertyChanged("Pwd");
				this.OnPwdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fname", DbType="NVarChar(50)")]
	public string Fname
	{
		get
		{
			return this._Fname;
		}
		set
		{
			if ((this._Fname != value))
			{
				this.OnFnameChanging(value);
				this.SendPropertyChanging();
				this._Fname = value;
				this.SendPropertyChanged("Fname");
				this.OnFnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mname", DbType="NVarChar(50)")]
	public string Mname
	{
		get
		{
			return this._Mname;
		}
		set
		{
			if ((this._Mname != value))
			{
				this.OnMnameChanging(value);
				this.SendPropertyChanging();
				this._Mname = value;
				this.SendPropertyChanged("Mname");
				this.OnMnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lname", DbType="NVarChar(50)")]
	public string Lname
	{
		get
		{
			return this._Lname;
		}
		set
		{
			if ((this._Lname != value))
			{
				this.OnLnameChanging(value);
				this.SendPropertyChanging();
				this._Lname = value;
				this.SendPropertyChanged("Lname");
				this.OnLnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="NVarChar(50)")]
	public string Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this.OnGenderChanging(value);
				this.SendPropertyChanging();
				this._Gender = value;
				this.SendPropertyChanged("Gender");
				this.OnGenderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(200)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country_id", DbType="Int")]
	public System.Nullable<int> Country_id
	{
		get
		{
			return this._Country_id;
		}
		set
		{
			if ((this._Country_id != value))
			{
				this.OnCountry_idChanging(value);
				this.SendPropertyChanging();
				this._Country_id = value;
				this.SendPropertyChanged("Country_id");
				this.OnCountry_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State_id", DbType="Int")]
	public System.Nullable<int> State_id
	{
		get
		{
			return this._State_id;
		}
		set
		{
			if ((this._State_id != value))
			{
				this.OnState_idChanging(value);
				this.SendPropertyChanging();
				this._State_id = value;
				this.SendPropertyChanged("State_id");
				this.OnState_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City_id", DbType="Int")]
	public System.Nullable<int> City_id
	{
		get
		{
			return this._City_id;
		}
		set
		{
			if ((this._City_id != value))
			{
				this.OnCity_idChanging(value);
				this.SendPropertyChanging();
				this._City_id = value;
				this.SendPropertyChanged("City_id");
				this.OnCity_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact_no", DbType="NVarChar(50)")]
	public string Contact_no
	{
		get
		{
			return this._Contact_no;
		}
		set
		{
			if ((this._Contact_no != value))
			{
				this.OnContact_noChanging(value);
				this.SendPropertyChanging();
				this._Contact_no = value;
				this.SendPropertyChanged("Contact_no");
				this.OnContact_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dob", DbType="NVarChar(50)")]
	public string Dob
	{
		get
		{
			return this._Dob;
		}
		set
		{
			if ((this._Dob != value))
			{
				this.OnDobChanging(value);
				this.SendPropertyChanging();
				this._Dob = value;
				this.SendPropertyChanged("Dob");
				this.OnDobChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Blood_group", DbType="NVarChar(50)")]
	public string Blood_group
	{
		get
		{
			return this._Blood_group;
		}
		set
		{
			if ((this._Blood_group != value))
			{
				this.OnBlood_groupChanging(value);
				this.SendPropertyChanging();
				this._Blood_group = value;
				this.SendPropertyChanged("Blood_group");
				this.OnBlood_groupChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postal_address", DbType="NVarChar(50)")]
	public string Postal_address
	{
		get
		{
			return this._Postal_address;
		}
		set
		{
			if ((this._Postal_address != value))
			{
				this.OnPostal_addressChanging(value);
				this.SendPropertyChanging();
				this._Postal_address = value;
				this.SendPropertyChanged("Postal_address");
				this.OnPostal_addressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_exper", DbType="NVarChar(50)")]
	public string Total_exper
	{
		get
		{
			return this._Total_exper;
		}
		set
		{
			if ((this._Total_exper != value))
			{
				this.OnTotal_experChanging(value);
				this.SendPropertyChanging();
				this._Total_exper = value;
				this.SendPropertyChanged("Total_exper");
				this.OnTotal_experChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sque_id", DbType="Int")]
	public System.Nullable<int> Sque_id
	{
		get
		{
			return this._Sque_id;
		}
		set
		{
			if ((this._Sque_id != value))
			{
				this.OnSque_idChanging(value);
				this.SendPropertyChanging();
				this._Sque_id = value;
				this.SendPropertyChanged("Sque_id");
				this.OnSque_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ans", DbType="NVarChar(100)")]
	public string Ans
	{
		get
		{
			return this._Ans;
		}
		set
		{
			if ((this._Ans != value))
			{
				this.OnAnsChanging(value);
				this.SendPropertyChanging();
				this._Ans = value;
				this.SendPropertyChanged("Ans");
				this.OnAnsChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
