#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="jobportaldb")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Inserttbl_state(tbl_state instance);
  partial void Updatetbl_state(tbl_state instance);
  partial void Deletetbl_state(tbl_state instance);
  partial void Inserttbl_sque(tbl_sque instance);
  partial void Updatetbl_sque(tbl_sque instance);
  partial void Deletetbl_sque(tbl_sque instance);
  partial void Inserttbl_country(tbl_country instance);
  partial void Updatetbl_country(tbl_country instance);
  partial void Deletetbl_country(tbl_country instance);
  partial void Inserttbl_city(tbl_city instance);
  partial void Updatetbl_city(tbl_city instance);
  partial void Deletetbl_city(tbl_city instance);
  partial void Inserttbl_expr(tbl_expr instance);
  partial void Updatetbl_expr(tbl_expr instance);
  partial void Deletetbl_expr(tbl_expr instance);
  partial void Inserttbl_resumefile(tbl_resumefile instance);
  partial void Updatetbl_resumefile(tbl_resumefile instance);
  partial void Deletetbl_resumefile(tbl_resumefile instance);
  partial void Inserttbl_job_type(tbl_job_type instance);
  partial void Updatetbl_job_type(tbl_job_type instance);
  partial void Deletetbl_job_type(tbl_job_type instance);
  partial void Inserttbl_jobseeker(tbl_jobseeker instance);
  partial void Updatetbl_jobseeker(tbl_jobseeker instance);
  partial void Deletetbl_jobseeker(tbl_jobseeker instance);
  partial void Inserttbl_job(tbl_job instance);
  partial void Updatetbl_job(tbl_job instance);
  partial void Deletetbl_job(tbl_job instance);
  partial void Inserttbl_employer(tbl_employer instance);
  partial void Updatetbl_employer(tbl_employer instance);
  partial void Deletetbl_employer(tbl_employer instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["jobportaldbConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tbl_state> tbl_states
	{
		get
		{
			return this.GetTable<tbl_state>();
		}
	}
	
	public System.Data.Linq.Table<tbl_sque> tbl_sques
	{
		get
		{
			return this.GetTable<tbl_sque>();
		}
	}
	
	public System.Data.Linq.Table<tbl_country> tbl_countries
	{
		get
		{
			return this.GetTable<tbl_country>();
		}
	}
	
	public System.Data.Linq.Table<tbl_city> tbl_cities
	{
		get
		{
			return this.GetTable<tbl_city>();
		}
	}
	
	public System.Data.Linq.Table<tbl_expr> tbl_exprs
	{
		get
		{
			return this.GetTable<tbl_expr>();
		}
	}
	
	public System.Data.Linq.Table<tbl_education> tbl_educations
	{
		get
		{
			return this.GetTable<tbl_education>();
		}
	}
	
	public System.Data.Linq.Table<tbl_resumefile> tbl_resumefiles
	{
		get
		{
			return this.GetTable<tbl_resumefile>();
		}
	}
	
	public System.Data.Linq.Table<tbl_job_type> tbl_job_types
	{
		get
		{
			return this.GetTable<tbl_job_type>();
		}
	}
	
	public System.Data.Linq.Table<tbl_jobseeker> tbl_jobseekers
	{
		get
		{
			return this.GetTable<tbl_jobseeker>();
		}
	}
	
	public System.Data.Linq.Table<tbl_job> tbl_jobs
	{
		get
		{
			return this.GetTable<tbl_job>();
		}
	}
	
	public System.Data.Linq.Table<tbl_employer> tbl_employers
	{
		get
		{
			return this.GetTable<tbl_employer>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertexpr")]
	public int insertexpr([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> js_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string company_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string contact_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string contact_no, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> country_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> state_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> city_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string post, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string from_date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string to_date)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), js_id, company_name, contact_name, contact_no, address, country_id, state_id, city_id, post, from_date, to_date);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.inserteducation")]
	public int inserteducation([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> js_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string degree, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string university, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> percentage, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string passing_year)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), js_id, degree, university, percentage, passing_year);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertresume")]
	public int insertresume([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string rs_file_path, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> js_id)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rs_file_path, js_id);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updatejobseeker")]
	public int updatejobseeker([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> js_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string fname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string mname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string lname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string gender, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> country_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> state_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> city_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string contact_no, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string dob, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string blood_group, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string postal_address, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> total_expr)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), js_id, fname, mname, lname, gender, address, country_id, state_id, city_id, contact_no, dob, blood_group, postal_address, total_expr);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updateeducation")]
	public int updateeducation([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> js_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string degree, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string university, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> percentage, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string passing_year)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), js_id, degree, university, percentage, passing_year);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updateexpr")]
	public int updateexpr([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> js_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string company_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string contact_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string contact_no, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> country_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> state_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> city_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string post, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string from_date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string to_date)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), js_id, company_name, contact_name, contact_no, address, country_id, state_id, city_id, post, from_date, to_date);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertjobseeker")]
	public int insertjobseeker(
				[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string email_id, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string pwd, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string fname, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string mname, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string lname, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string gender, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string address, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> country_id, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> state_id, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> city_id, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string contact_no, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string dob, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string blood_group, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string postal_address, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> total_expr, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sque_id, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string answer, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> flag)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email_id, pwd, fname, mname, lname, gender, address, country_id, state_id, city_id, contact_no, dob, blood_group, postal_address, total_expr, sque_id, answer, flag);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertpost")]
	public int insertpost([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> employer_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> min_exp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> min_sal, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> max_sal, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string education, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> de_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> job_type, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string post_date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> validity, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string job_dis)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), employer_id, min_exp, min_sal, max_sal, education, de_id, job_type, post_date, validity, job_dis);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertemployeer")]
	public int insertemployeer([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string email_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string company_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string pwd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> country_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> state_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> city_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string contact_no, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string logo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string tagline, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string cdiscription, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sque_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string answer)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email_id, company_name, pwd, address, country_id, state_id, city_id, contact_no, logo, tagline, cdiscription, sque_id, answer);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updateemployerprofile1")]
	public int updateemployerprofile1([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> employer_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string email_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string company_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string contact_no, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string logo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string tagline, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string cdiscription, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> country_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> state_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> city_id)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), employer_id, email_id, company_name, contact_no, logo, tagline, cdiscription, address, country_id, state_id, city_id);
		return ((int)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_state")]
public partial class tbl_state : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _state_id;
	
	private string _state_name;
	
	private int _country_id;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onstate_idChanging(int value);
    partial void Onstate_idChanged();
    partial void Onstate_nameChanging(string value);
    partial void Onstate_nameChanged();
    partial void Oncountry_idChanging(int value);
    partial void Oncountry_idChanged();
    #endregion
	
	public tbl_state()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int state_id
	{
		get
		{
			return this._state_id;
		}
		set
		{
			if ((this._state_id != value))
			{
				this.Onstate_idChanging(value);
				this.SendPropertyChanging();
				this._state_id = value;
				this.SendPropertyChanged("state_id");
				this.Onstate_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string state_name
	{
		get
		{
			return this._state_name;
		}
		set
		{
			if ((this._state_name != value))
			{
				this.Onstate_nameChanging(value);
				this.SendPropertyChanging();
				this._state_name = value;
				this.SendPropertyChanged("state_name");
				this.Onstate_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country_id", DbType="Int NOT NULL")]
	public int country_id
	{
		get
		{
			return this._country_id;
		}
		set
		{
			if ((this._country_id != value))
			{
				this.Oncountry_idChanging(value);
				this.SendPropertyChanging();
				this._country_id = value;
				this.SendPropertyChanged("country_id");
				this.Oncountry_idChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_sque")]
public partial class tbl_sque : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _sque_id;
	
	private string _sque;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsque_idChanging(int value);
    partial void Onsque_idChanged();
    partial void OnsqueChanging(string value);
    partial void OnsqueChanged();
    #endregion
	
	public tbl_sque()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sque_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int sque_id
	{
		get
		{
			return this._sque_id;
		}
		set
		{
			if ((this._sque_id != value))
			{
				this.Onsque_idChanging(value);
				this.SendPropertyChanging();
				this._sque_id = value;
				this.SendPropertyChanged("sque_id");
				this.Onsque_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sque", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string sque
	{
		get
		{
			return this._sque;
		}
		set
		{
			if ((this._sque != value))
			{
				this.OnsqueChanging(value);
				this.SendPropertyChanging();
				this._sque = value;
				this.SendPropertyChanged("sque");
				this.OnsqueChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_country")]
public partial class tbl_country : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _country_id;
	
	private string _country_name;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncountry_idChanging(int value);
    partial void Oncountry_idChanged();
    partial void Oncountry_nameChanging(string value);
    partial void Oncountry_nameChanged();
    #endregion
	
	public tbl_country()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int country_id
	{
		get
		{
			return this._country_id;
		}
		set
		{
			if ((this._country_id != value))
			{
				this.Oncountry_idChanging(value);
				this.SendPropertyChanging();
				this._country_id = value;
				this.SendPropertyChanged("country_id");
				this.Oncountry_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string country_name
	{
		get
		{
			return this._country_name;
		}
		set
		{
			if ((this._country_name != value))
			{
				this.Oncountry_nameChanging(value);
				this.SendPropertyChanging();
				this._country_name = value;
				this.SendPropertyChanged("country_name");
				this.Oncountry_nameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_city")]
public partial class tbl_city : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _city_id;
	
	private string _city_name;
	
	private int _state_id;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncity_idChanging(int value);
    partial void Oncity_idChanged();
    partial void Oncity_nameChanging(string value);
    partial void Oncity_nameChanged();
    partial void Onstate_idChanging(int value);
    partial void Onstate_idChanged();
    #endregion
	
	public tbl_city()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int city_id
	{
		get
		{
			return this._city_id;
		}
		set
		{
			if ((this._city_id != value))
			{
				this.Oncity_idChanging(value);
				this.SendPropertyChanging();
				this._city_id = value;
				this.SendPropertyChanged("city_id");
				this.Oncity_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string city_name
	{
		get
		{
			return this._city_name;
		}
		set
		{
			if ((this._city_name != value))
			{
				this.Oncity_nameChanging(value);
				this.SendPropertyChanging();
				this._city_name = value;
				this.SendPropertyChanged("city_name");
				this.Oncity_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_id", DbType="Int NOT NULL")]
	public int state_id
	{
		get
		{
			return this._state_id;
		}
		set
		{
			if ((this._state_id != value))
			{
				this.Onstate_idChanging(value);
				this.SendPropertyChanging();
				this._state_id = value;
				this.SendPropertyChanged("state_id");
				this.Onstate_idChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_expr")]
public partial class tbl_expr : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _expr_id;
	
	private int _js_id;
	
	private string _company_name;
	
	private string _contact_name;
	
	private string _contact_no;
	
	private string _address;
	
	private int _country_id;
	
	private int _state_id;
	
	private int _city_id;
	
	private string _post;
	
	private string _from_date;
	
	private string _to_date;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onexpr_idChanging(int value);
    partial void Onexpr_idChanged();
    partial void Onjs_idChanging(int value);
    partial void Onjs_idChanged();
    partial void Oncompany_nameChanging(string value);
    partial void Oncompany_nameChanged();
    partial void Oncontact_nameChanging(string value);
    partial void Oncontact_nameChanged();
    partial void Oncontact_noChanging(string value);
    partial void Oncontact_noChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void Oncountry_idChanging(int value);
    partial void Oncountry_idChanged();
    partial void Onstate_idChanging(int value);
    partial void Onstate_idChanged();
    partial void Oncity_idChanging(int value);
    partial void Oncity_idChanged();
    partial void OnpostChanging(string value);
    partial void OnpostChanged();
    partial void Onfrom_dateChanging(string value);
    partial void Onfrom_dateChanged();
    partial void Onto_dateChanging(string value);
    partial void Onto_dateChanged();
    #endregion
	
	public tbl_expr()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expr_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int expr_id
	{
		get
		{
			return this._expr_id;
		}
		set
		{
			if ((this._expr_id != value))
			{
				this.Onexpr_idChanging(value);
				this.SendPropertyChanging();
				this._expr_id = value;
				this.SendPropertyChanged("expr_id");
				this.Onexpr_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_js_id", DbType="Int NOT NULL")]
	public int js_id
	{
		get
		{
			return this._js_id;
		}
		set
		{
			if ((this._js_id != value))
			{
				this.Onjs_idChanging(value);
				this.SendPropertyChanging();
				this._js_id = value;
				this.SendPropertyChanged("js_id");
				this.Onjs_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string company_name
	{
		get
		{
			return this._company_name;
		}
		set
		{
			if ((this._company_name != value))
			{
				this.Oncompany_nameChanging(value);
				this.SendPropertyChanging();
				this._company_name = value;
				this.SendPropertyChanged("company_name");
				this.Oncompany_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string contact_name
	{
		get
		{
			return this._contact_name;
		}
		set
		{
			if ((this._contact_name != value))
			{
				this.Oncontact_nameChanging(value);
				this.SendPropertyChanging();
				this._contact_name = value;
				this.SendPropertyChanged("contact_name");
				this.Oncontact_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact_no", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string contact_no
	{
		get
		{
			return this._contact_no;
		}
		set
		{
			if ((this._contact_no != value))
			{
				this.Oncontact_noChanging(value);
				this.SendPropertyChanging();
				this._contact_no = value;
				this.SendPropertyChanged("contact_no");
				this.Oncontact_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string address
	{
		get
		{
			return this._address;
		}
		set
		{
			if ((this._address != value))
			{
				this.OnaddressChanging(value);
				this.SendPropertyChanging();
				this._address = value;
				this.SendPropertyChanged("address");
				this.OnaddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country_id", DbType="Int NOT NULL")]
	public int country_id
	{
		get
		{
			return this._country_id;
		}
		set
		{
			if ((this._country_id != value))
			{
				this.Oncountry_idChanging(value);
				this.SendPropertyChanging();
				this._country_id = value;
				this.SendPropertyChanged("country_id");
				this.Oncountry_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_id", DbType="Int NOT NULL")]
	public int state_id
	{
		get
		{
			return this._state_id;
		}
		set
		{
			if ((this._state_id != value))
			{
				this.Onstate_idChanging(value);
				this.SendPropertyChanging();
				this._state_id = value;
				this.SendPropertyChanged("state_id");
				this.Onstate_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city_id", DbType="Int NOT NULL")]
	public int city_id
	{
		get
		{
			return this._city_id;
		}
		set
		{
			if ((this._city_id != value))
			{
				this.Oncity_idChanging(value);
				this.SendPropertyChanging();
				this._city_id = value;
				this.SendPropertyChanged("city_id");
				this.Oncity_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_post", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string post
	{
		get
		{
			return this._post;
		}
		set
		{
			if ((this._post != value))
			{
				this.OnpostChanging(value);
				this.SendPropertyChanging();
				this._post = value;
				this.SendPropertyChanged("post");
				this.OnpostChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_from_date", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string from_date
	{
		get
		{
			return this._from_date;
		}
		set
		{
			if ((this._from_date != value))
			{
				this.Onfrom_dateChanging(value);
				this.SendPropertyChanging();
				this._from_date = value;
				this.SendPropertyChanged("from_date");
				this.Onfrom_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_to_date", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string to_date
	{
		get
		{
			return this._to_date;
		}
		set
		{
			if ((this._to_date != value))
			{
				this.Onto_dateChanging(value);
				this.SendPropertyChanging();
				this._to_date = value;
				this.SendPropertyChanged("to_date");
				this.Onto_dateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_education")]
public partial class tbl_education
{
	
	private int _js_id;
	
	private string _degree;
	
	private string _university;
	
	private double _percentage;
	
	private string _passing_year;
	
	public tbl_education()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_js_id", DbType="Int NOT NULL")]
	public int js_id
	{
		get
		{
			return this._js_id;
		}
		set
		{
			if ((this._js_id != value))
			{
				this._js_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_degree", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string degree
	{
		get
		{
			return this._degree;
		}
		set
		{
			if ((this._degree != value))
			{
				this._degree = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_university", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string university
	{
		get
		{
			return this._university;
		}
		set
		{
			if ((this._university != value))
			{
				this._university = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_percentage", DbType="Float NOT NULL")]
	public double percentage
	{
		get
		{
			return this._percentage;
		}
		set
		{
			if ((this._percentage != value))
			{
				this._percentage = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passing_year", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string passing_year
	{
		get
		{
			return this._passing_year;
		}
		set
		{
			if ((this._passing_year != value))
			{
				this._passing_year = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_resumefile")]
public partial class tbl_resumefile : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _rs_id;
	
	private string _rs_file_path;
	
	private int _js_id;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onrs_idChanging(int value);
    partial void Onrs_idChanged();
    partial void Onrs_file_pathChanging(string value);
    partial void Onrs_file_pathChanged();
    partial void Onjs_idChanging(int value);
    partial void Onjs_idChanged();
    #endregion
	
	public tbl_resumefile()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rs_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int rs_id
	{
		get
		{
			return this._rs_id;
		}
		set
		{
			if ((this._rs_id != value))
			{
				this.Onrs_idChanging(value);
				this.SendPropertyChanging();
				this._rs_id = value;
				this.SendPropertyChanged("rs_id");
				this.Onrs_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rs_file_path", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string rs_file_path
	{
		get
		{
			return this._rs_file_path;
		}
		set
		{
			if ((this._rs_file_path != value))
			{
				this.Onrs_file_pathChanging(value);
				this.SendPropertyChanging();
				this._rs_file_path = value;
				this.SendPropertyChanged("rs_file_path");
				this.Onrs_file_pathChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_js_id", DbType="Int NOT NULL")]
	public int js_id
	{
		get
		{
			return this._js_id;
		}
		set
		{
			if ((this._js_id != value))
			{
				this.Onjs_idChanging(value);
				this.SendPropertyChanging();
				this._js_id = value;
				this.SendPropertyChanged("js_id");
				this.Onjs_idChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_job_type")]
public partial class tbl_job_type : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _job_type_id;
	
	private string _job_type_name;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onjob_type_idChanging(int value);
    partial void Onjob_type_idChanged();
    partial void Onjob_type_nameChanging(string value);
    partial void Onjob_type_nameChanged();
    #endregion
	
	public tbl_job_type()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_type_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int job_type_id
	{
		get
		{
			return this._job_type_id;
		}
		set
		{
			if ((this._job_type_id != value))
			{
				this.Onjob_type_idChanging(value);
				this.SendPropertyChanging();
				this._job_type_id = value;
				this.SendPropertyChanged("job_type_id");
				this.Onjob_type_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_type_name", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
	public string job_type_name
	{
		get
		{
			return this._job_type_name;
		}
		set
		{
			if ((this._job_type_name != value))
			{
				this.Onjob_type_nameChanging(value);
				this.SendPropertyChanging();
				this._job_type_name = value;
				this.SendPropertyChanged("job_type_name");
				this.Onjob_type_nameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_jobseeker")]
public partial class tbl_jobseeker : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _js_id;
	
	private string _email_id;
	
	private string _pwd;
	
	private string _fname;
	
	private string _mname;
	
	private string _lname;
	
	private string _gender;
	
	private string _address;
	
	private int _country_id;
	
	private int _state_id;
	
	private int _city_id;
	
	private string _contact_no;
	
	private string _dob;
	
	private string _blood_group;
	
	private string _postal_address;
	
	private int _total_expr;
	
	private int _sque_id;
	
	private string _answer;
	
	private System.Nullable<int> _flag;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onjs_idChanging(int value);
    partial void Onjs_idChanged();
    partial void Onemail_idChanging(string value);
    partial void Onemail_idChanged();
    partial void OnpwdChanging(string value);
    partial void OnpwdChanged();
    partial void OnfnameChanging(string value);
    partial void OnfnameChanged();
    partial void OnmnameChanging(string value);
    partial void OnmnameChanged();
    partial void OnlnameChanging(string value);
    partial void OnlnameChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void Oncountry_idChanging(int value);
    partial void Oncountry_idChanged();
    partial void Onstate_idChanging(int value);
    partial void Onstate_idChanged();
    partial void Oncity_idChanging(int value);
    partial void Oncity_idChanged();
    partial void Oncontact_noChanging(string value);
    partial void Oncontact_noChanged();
    partial void OndobChanging(string value);
    partial void OndobChanged();
    partial void Onblood_groupChanging(string value);
    partial void Onblood_groupChanged();
    partial void Onpostal_addressChanging(string value);
    partial void Onpostal_addressChanged();
    partial void Ontotal_exprChanging(int value);
    partial void Ontotal_exprChanged();
    partial void Onsque_idChanging(int value);
    partial void Onsque_idChanged();
    partial void OnanswerChanging(string value);
    partial void OnanswerChanged();
    partial void OnflagChanging(System.Nullable<int> value);
    partial void OnflagChanged();
    #endregion
	
	public tbl_jobseeker()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_js_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int js_id
	{
		get
		{
			return this._js_id;
		}
		set
		{
			if ((this._js_id != value))
			{
				this.Onjs_idChanging(value);
				this.SendPropertyChanging();
				this._js_id = value;
				this.SendPropertyChanged("js_id");
				this.Onjs_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email_id", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string email_id
	{
		get
		{
			return this._email_id;
		}
		set
		{
			if ((this._email_id != value))
			{
				this.Onemail_idChanging(value);
				this.SendPropertyChanging();
				this._email_id = value;
				this.SendPropertyChanged("email_id");
				this.Onemail_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwd", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string pwd
	{
		get
		{
			return this._pwd;
		}
		set
		{
			if ((this._pwd != value))
			{
				this.OnpwdChanging(value);
				this.SendPropertyChanging();
				this._pwd = value;
				this.SendPropertyChanged("pwd");
				this.OnpwdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string fname
	{
		get
		{
			return this._fname;
		}
		set
		{
			if ((this._fname != value))
			{
				this.OnfnameChanging(value);
				this.SendPropertyChanging();
				this._fname = value;
				this.SendPropertyChanged("fname");
				this.OnfnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string mname
	{
		get
		{
			return this._mname;
		}
		set
		{
			if ((this._mname != value))
			{
				this.OnmnameChanging(value);
				this.SendPropertyChanging();
				this._mname = value;
				this.SendPropertyChanged("mname");
				this.OnmnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string lname
	{
		get
		{
			return this._lname;
		}
		set
		{
			if ((this._lname != value))
			{
				this.OnlnameChanging(value);
				this.SendPropertyChanging();
				this._lname = value;
				this.SendPropertyChanged("lname");
				this.OnlnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string gender
	{
		get
		{
			return this._gender;
		}
		set
		{
			if ((this._gender != value))
			{
				this.OngenderChanging(value);
				this.SendPropertyChanging();
				this._gender = value;
				this.SendPropertyChanged("gender");
				this.OngenderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string address
	{
		get
		{
			return this._address;
		}
		set
		{
			if ((this._address != value))
			{
				this.OnaddressChanging(value);
				this.SendPropertyChanging();
				this._address = value;
				this.SendPropertyChanged("address");
				this.OnaddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country_id", DbType="Int NOT NULL")]
	public int country_id
	{
		get
		{
			return this._country_id;
		}
		set
		{
			if ((this._country_id != value))
			{
				this.Oncountry_idChanging(value);
				this.SendPropertyChanging();
				this._country_id = value;
				this.SendPropertyChanged("country_id");
				this.Oncountry_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_id", DbType="Int NOT NULL")]
	public int state_id
	{
		get
		{
			return this._state_id;
		}
		set
		{
			if ((this._state_id != value))
			{
				this.Onstate_idChanging(value);
				this.SendPropertyChanging();
				this._state_id = value;
				this.SendPropertyChanged("state_id");
				this.Onstate_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city_id", DbType="Int NOT NULL")]
	public int city_id
	{
		get
		{
			return this._city_id;
		}
		set
		{
			if ((this._city_id != value))
			{
				this.Oncity_idChanging(value);
				this.SendPropertyChanging();
				this._city_id = value;
				this.SendPropertyChanged("city_id");
				this.Oncity_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact_no", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
	public string contact_no
	{
		get
		{
			return this._contact_no;
		}
		set
		{
			if ((this._contact_no != value))
			{
				this.Oncontact_noChanging(value);
				this.SendPropertyChanging();
				this._contact_no = value;
				this.SendPropertyChanged("contact_no");
				this.Oncontact_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dob", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string dob
	{
		get
		{
			return this._dob;
		}
		set
		{
			if ((this._dob != value))
			{
				this.OndobChanging(value);
				this.SendPropertyChanging();
				this._dob = value;
				this.SendPropertyChanged("dob");
				this.OndobChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_blood_group", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string blood_group
	{
		get
		{
			return this._blood_group;
		}
		set
		{
			if ((this._blood_group != value))
			{
				this.Onblood_groupChanging(value);
				this.SendPropertyChanging();
				this._blood_group = value;
				this.SendPropertyChanged("blood_group");
				this.Onblood_groupChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postal_address", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string postal_address
	{
		get
		{
			return this._postal_address;
		}
		set
		{
			if ((this._postal_address != value))
			{
				this.Onpostal_addressChanging(value);
				this.SendPropertyChanging();
				this._postal_address = value;
				this.SendPropertyChanged("postal_address");
				this.Onpostal_addressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_expr", DbType="Int NOT NULL")]
	public int total_expr
	{
		get
		{
			return this._total_expr;
		}
		set
		{
			if ((this._total_expr != value))
			{
				this.Ontotal_exprChanging(value);
				this.SendPropertyChanging();
				this._total_expr = value;
				this.SendPropertyChanged("total_expr");
				this.Ontotal_exprChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sque_id", DbType="Int NOT NULL")]
	public int sque_id
	{
		get
		{
			return this._sque_id;
		}
		set
		{
			if ((this._sque_id != value))
			{
				this.Onsque_idChanging(value);
				this.SendPropertyChanging();
				this._sque_id = value;
				this.SendPropertyChanged("sque_id");
				this.Onsque_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string answer
	{
		get
		{
			return this._answer;
		}
		set
		{
			if ((this._answer != value))
			{
				this.OnanswerChanging(value);
				this.SendPropertyChanging();
				this._answer = value;
				this.SendPropertyChanged("answer");
				this.OnanswerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flag", DbType="Int")]
	public System.Nullable<int> flag
	{
		get
		{
			return this._flag;
		}
		set
		{
			if ((this._flag != value))
			{
				this.OnflagChanging(value);
				this.SendPropertyChanging();
				this._flag = value;
				this.SendPropertyChanged("flag");
				this.OnflagChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_job")]
public partial class tbl_job : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _job_id;
	
	private int _employer_id;
	
	private int _min_exp;
	
	private int _min_sal;
	
	private int _max_sal;
	
	private string _education;
	
	private int _de_id;
	
	private int _job_type_id;
	
	private string _post_date;
	
	private int _validity;
	
	private string _job_dis;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onjob_idChanging(int value);
    partial void Onjob_idChanged();
    partial void Onemployer_idChanging(int value);
    partial void Onemployer_idChanged();
    partial void Onmin_expChanging(int value);
    partial void Onmin_expChanged();
    partial void Onmin_salChanging(int value);
    partial void Onmin_salChanged();
    partial void Onmax_salChanging(int value);
    partial void Onmax_salChanged();
    partial void OneducationChanging(string value);
    partial void OneducationChanged();
    partial void Onde_idChanging(int value);
    partial void Onde_idChanged();
    partial void Onjob_type_idChanging(int value);
    partial void Onjob_type_idChanged();
    partial void Onpost_dateChanging(string value);
    partial void Onpost_dateChanged();
    partial void OnvalidityChanging(int value);
    partial void OnvalidityChanged();
    partial void Onjob_disChanging(string value);
    partial void Onjob_disChanged();
    #endregion
	
	public tbl_job()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int job_id
	{
		get
		{
			return this._job_id;
		}
		set
		{
			if ((this._job_id != value))
			{
				this.Onjob_idChanging(value);
				this.SendPropertyChanging();
				this._job_id = value;
				this.SendPropertyChanged("job_id");
				this.Onjob_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employer_id", DbType="Int NOT NULL")]
	public int employer_id
	{
		get
		{
			return this._employer_id;
		}
		set
		{
			if ((this._employer_id != value))
			{
				this.Onemployer_idChanging(value);
				this.SendPropertyChanging();
				this._employer_id = value;
				this.SendPropertyChanged("employer_id");
				this.Onemployer_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_min_exp", DbType="Int NOT NULL")]
	public int min_exp
	{
		get
		{
			return this._min_exp;
		}
		set
		{
			if ((this._min_exp != value))
			{
				this.Onmin_expChanging(value);
				this.SendPropertyChanging();
				this._min_exp = value;
				this.SendPropertyChanged("min_exp");
				this.Onmin_expChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_min_sal", DbType="Int NOT NULL")]
	public int min_sal
	{
		get
		{
			return this._min_sal;
		}
		set
		{
			if ((this._min_sal != value))
			{
				this.Onmin_salChanging(value);
				this.SendPropertyChanging();
				this._min_sal = value;
				this.SendPropertyChanged("min_sal");
				this.Onmin_salChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_max_sal", DbType="Int NOT NULL")]
	public int max_sal
	{
		get
		{
			return this._max_sal;
		}
		set
		{
			if ((this._max_sal != value))
			{
				this.Onmax_salChanging(value);
				this.SendPropertyChanging();
				this._max_sal = value;
				this.SendPropertyChanged("max_sal");
				this.Onmax_salChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_education", DbType="VarChar(100)")]
	public string education
	{
		get
		{
			return this._education;
		}
		set
		{
			if ((this._education != value))
			{
				this.OneducationChanging(value);
				this.SendPropertyChanging();
				this._education = value;
				this.SendPropertyChanged("education");
				this.OneducationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_de_id", DbType="Int NOT NULL")]
	public int de_id
	{
		get
		{
			return this._de_id;
		}
		set
		{
			if ((this._de_id != value))
			{
				this.Onde_idChanging(value);
				this.SendPropertyChanging();
				this._de_id = value;
				this.SendPropertyChanged("de_id");
				this.Onde_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_type_id", DbType="Int NOT NULL")]
	public int job_type_id
	{
		get
		{
			return this._job_type_id;
		}
		set
		{
			if ((this._job_type_id != value))
			{
				this.Onjob_type_idChanging(value);
				this.SendPropertyChanging();
				this._job_type_id = value;
				this.SendPropertyChanged("job_type_id");
				this.Onjob_type_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_post_date", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string post_date
	{
		get
		{
			return this._post_date;
		}
		set
		{
			if ((this._post_date != value))
			{
				this.Onpost_dateChanging(value);
				this.SendPropertyChanging();
				this._post_date = value;
				this.SendPropertyChanged("post_date");
				this.Onpost_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_validity", DbType="Int NOT NULL")]
	public int validity
	{
		get
		{
			return this._validity;
		}
		set
		{
			if ((this._validity != value))
			{
				this.OnvalidityChanging(value);
				this.SendPropertyChanging();
				this._validity = value;
				this.SendPropertyChanged("validity");
				this.OnvalidityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_dis", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string job_dis
	{
		get
		{
			return this._job_dis;
		}
		set
		{
			if ((this._job_dis != value))
			{
				this.Onjob_disChanging(value);
				this.SendPropertyChanging();
				this._job_dis = value;
				this.SendPropertyChanged("job_dis");
				this.Onjob_disChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_employer")]
public partial class tbl_employer : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _employer_id;
	
	private string _email_id;
	
	private string _pwd;
	
	private string _company_name;
	
	private string _contact_no;
	
	private string _logo;
	
	private string _tagline;
	
	private string _cdiscription;
	
	private string _address;
	
	private int _country_id;
	
	private int _state_id;
	
	private int _city_id;
	
	private int _sque_id;
	
	private string _answer;
	
	private int _flag;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onemployer_idChanging(int value);
    partial void Onemployer_idChanged();
    partial void Onemail_idChanging(string value);
    partial void Onemail_idChanged();
    partial void OnpwdChanging(string value);
    partial void OnpwdChanged();
    partial void Oncompany_nameChanging(string value);
    partial void Oncompany_nameChanged();
    partial void Oncontact_noChanging(string value);
    partial void Oncontact_noChanged();
    partial void OnlogoChanging(string value);
    partial void OnlogoChanged();
    partial void OntaglineChanging(string value);
    partial void OntaglineChanged();
    partial void OncdiscriptionChanging(string value);
    partial void OncdiscriptionChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void Oncountry_idChanging(int value);
    partial void Oncountry_idChanged();
    partial void Onstate_idChanging(int value);
    partial void Onstate_idChanged();
    partial void Oncity_idChanging(int value);
    partial void Oncity_idChanged();
    partial void Onsque_idChanging(int value);
    partial void Onsque_idChanged();
    partial void OnanswerChanging(string value);
    partial void OnanswerChanged();
    partial void OnflagChanging(int value);
    partial void OnflagChanged();
    #endregion
	
	public tbl_employer()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employer_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int employer_id
	{
		get
		{
			return this._employer_id;
		}
		set
		{
			if ((this._employer_id != value))
			{
				this.Onemployer_idChanging(value);
				this.SendPropertyChanging();
				this._employer_id = value;
				this.SendPropertyChanged("employer_id");
				this.Onemployer_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email_id", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string email_id
	{
		get
		{
			return this._email_id;
		}
		set
		{
			if ((this._email_id != value))
			{
				this.Onemail_idChanging(value);
				this.SendPropertyChanging();
				this._email_id = value;
				this.SendPropertyChanged("email_id");
				this.Onemail_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwd", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string pwd
	{
		get
		{
			return this._pwd;
		}
		set
		{
			if ((this._pwd != value))
			{
				this.OnpwdChanging(value);
				this.SendPropertyChanging();
				this._pwd = value;
				this.SendPropertyChanged("pwd");
				this.OnpwdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string company_name
	{
		get
		{
			return this._company_name;
		}
		set
		{
			if ((this._company_name != value))
			{
				this.Oncompany_nameChanging(value);
				this.SendPropertyChanging();
				this._company_name = value;
				this.SendPropertyChanged("company_name");
				this.Oncompany_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact_no", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string contact_no
	{
		get
		{
			return this._contact_no;
		}
		set
		{
			if ((this._contact_no != value))
			{
				this.Oncontact_noChanging(value);
				this.SendPropertyChanging();
				this._contact_no = value;
				this.SendPropertyChanged("contact_no");
				this.Oncontact_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logo", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string logo
	{
		get
		{
			return this._logo;
		}
		set
		{
			if ((this._logo != value))
			{
				this.OnlogoChanging(value);
				this.SendPropertyChanging();
				this._logo = value;
				this.SendPropertyChanged("logo");
				this.OnlogoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tagline", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string tagline
	{
		get
		{
			return this._tagline;
		}
		set
		{
			if ((this._tagline != value))
			{
				this.OntaglineChanging(value);
				this.SendPropertyChanging();
				this._tagline = value;
				this.SendPropertyChanged("tagline");
				this.OntaglineChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cdiscription", DbType="VarChar(MAX)")]
	public string cdiscription
	{
		get
		{
			return this._cdiscription;
		}
		set
		{
			if ((this._cdiscription != value))
			{
				this.OncdiscriptionChanging(value);
				this.SendPropertyChanging();
				this._cdiscription = value;
				this.SendPropertyChanged("cdiscription");
				this.OncdiscriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string address
	{
		get
		{
			return this._address;
		}
		set
		{
			if ((this._address != value))
			{
				this.OnaddressChanging(value);
				this.SendPropertyChanging();
				this._address = value;
				this.SendPropertyChanged("address");
				this.OnaddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country_id", DbType="Int NOT NULL")]
	public int country_id
	{
		get
		{
			return this._country_id;
		}
		set
		{
			if ((this._country_id != value))
			{
				this.Oncountry_idChanging(value);
				this.SendPropertyChanging();
				this._country_id = value;
				this.SendPropertyChanged("country_id");
				this.Oncountry_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_id", DbType="Int NOT NULL")]
	public int state_id
	{
		get
		{
			return this._state_id;
		}
		set
		{
			if ((this._state_id != value))
			{
				this.Onstate_idChanging(value);
				this.SendPropertyChanging();
				this._state_id = value;
				this.SendPropertyChanged("state_id");
				this.Onstate_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city_id", DbType="Int NOT NULL")]
	public int city_id
	{
		get
		{
			return this._city_id;
		}
		set
		{
			if ((this._city_id != value))
			{
				this.Oncity_idChanging(value);
				this.SendPropertyChanging();
				this._city_id = value;
				this.SendPropertyChanged("city_id");
				this.Oncity_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sque_id", DbType="Int NOT NULL")]
	public int sque_id
	{
		get
		{
			return this._sque_id;
		}
		set
		{
			if ((this._sque_id != value))
			{
				this.Onsque_idChanging(value);
				this.SendPropertyChanging();
				this._sque_id = value;
				this.SendPropertyChanged("sque_id");
				this.Onsque_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string answer
	{
		get
		{
			return this._answer;
		}
		set
		{
			if ((this._answer != value))
			{
				this.OnanswerChanging(value);
				this.SendPropertyChanging();
				this._answer = value;
				this.SendPropertyChanged("answer");
				this.OnanswerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flag", DbType="Int NOT NULL")]
	public int flag
	{
		get
		{
			return this._flag;
		}
		set
		{
			if ((this._flag != value))
			{
				this.OnflagChanging(value);
				this.SendPropertyChanging();
				this._flag = value;
				this.SendPropertyChanged("flag");
				this.OnflagChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
